# Generated by Django 5.2.3 on 2025-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='vip',
            field=models.BooleanField(default=False, help_text='Check if this tenant is VIP and should see automated features.'),
        ),
    ]
