# Generated by Django 5.2.3 on 2025-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_knowledgebasecategory_knowledgebasearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text="Primary email domain for auto-assignment, e.g. 'reedminerals.com'", max_length=100, null=True, unique=True),
        ),
    ]
