# Generated by Django 5.2.3 on 2025-06-27 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_tenant_address_tenant_logo_tenant_main_poc_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('tips', 'Tips')], default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this announcement to the top for all tenants.'),
        ),
    ]
