# Generated by Django 5.2.3 on 2025-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_announcement_author_announcement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for this article', null=True, upload_to='kb_thumbnails/'),
        ),
    ]
