# Generated by Django 5.2.3 on 2025-06-30 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0009_knowledgebasearticle_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='auth.group'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
