# Generated by Django 5.2.3 on 2025-07-01 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_tenant_groups_tenant_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role_requested', models.CharField(max_length=50)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Optional: store form/automation metadata', null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='portal.tenant')),
            ],
        ),
    ]
