# Generated by Django 5.2.3 on 2025-07-02 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_pendinguserapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('last_status_id', models.IntegerField()),
                ('last_status_name', models.CharField(max_length=128)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ticket_id')},
            },
        ),
    ]
