# Generated by Django 5.2.3 on 2025-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
