# Generated by Django 4.2.23 on 2025-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_seed_core_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin Center'), ('client', 'Client Portal')], default='admin', help_text='Role scope: admin or client', max_length=16),
        ),
    ]
