# Generated by Django 4.2.23 on 2025-07-07 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_tenant_industry_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='priority_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vip_level',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Custom', 'Custom')], max_length=32, null=True),
        ),
    ]
