# Generated by Django 4.2.23 on 2025-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_knowledgebasearticle_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('hidden', 'Hidden')], default='public', max_length=20),
        ),
    ]
