"""
Django settings for buckeyeit_portal project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&y*ld2(2yt9#e5)+u_mnq(fns-fg28jyan8aco&96ljyohl5wm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal.apps.PortalConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'buckeyeit_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'buckeyeit_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://USER :PASSWORD@HOST:5432/DBNAME',
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'portal' / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'portal.User'

# django-allauth config
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/login/'

# Email verification settings for allauth
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification
ACCOUNT_EMAIL_REQUIRED = False  # Don't require email for social accounts
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create user accounts for social logins
SOCIALACCOUNT_EMAIL_REQUIRED = False  # Don't require email for social accounts

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'TENANT': 'common', # or your tenant ID
        'SCOPE': ['User.Read'],
        'AUTH_PARAMS': {'prompt': 'select_account'},
    }
}

ACCOUNT_ADAPTER = 'portal.adapters.NoNewUsersAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'portal.adapters.CustomSocialAccountAdapter'

CSRF_TRUSTED_ORIGINS = [
    "https://portal.buckeyeit.com",
    "http://portal.buckeyeit.com"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

JAZZMIN_SETTINGS = {
    "site_title": "Buckeye IT Admin",
    "site_header": "Buckeye IT Portal",
    "site_brand": "Buckeye IT",
    "site_logo": "portal/assets/buckeye-logo.png",
    "login_logo": "portal/assets/buckeye-logo.png",
    "welcome_sign": "Welcome to Buckeye IT Admin Portal",
    "copyright": "Buckeye IT",
    "primary_color": "#c8102e",
    "secondary_color": "#505050",
    "accent": "#c8102e",
    "navbar": "#505050",
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
}

# ConnectWise API credentials (move to environment variables for production!)
CONNECTWISE_SITE = "https://na.myconnectwise.net"
CONNECTWISE_COMPANY_ID = "buckeyeitser"
CONNECTWISE_PUBLIC_KEY = "d3oNPUMCjzbkOj47"
CONNECTWISE_PRIVATE_KEY = "LPAtfIRn8GCiRez3"
CONNECTWISE_CLIENT_ID = "173d3199-c79d-4219-88ba-96140f77942e"
